DEFAULTS: &DEFAULTS
  pool: 8
  adapter: postgresql
  encoding: utf8
  password:

test:
  database: media_server_test
  <<: *DEFAULTS

development:
  database: media_server_development
  <<: *DEFAULTS

production:
  database: media_server_production
  <<: *DEFAULTS
